In [3]:
import pandas as pd 
import numpy as np

In [4]:
Pakistan_T20_Matches_Information = pd.read_csv("Pakistan_T20_Matches_Information.csv")
matches_info = pd.read_csv(r"C:\Users\4A\Documents\projects\New folder\match_info.csv")
plyaer_name = pd.read_csv(r"C:\Users\4A\Documents\projects\New folder\Player_name.csv")

**PLAYER NAME CSV CLEANING**

In [5]:
plyaer_name = plyaer_name.drop("Unnamed: 0",axis=1)  #droped the unecessary column

In [6]:
#file cleaning process
plyaer_name['name'] = plyaer_name['name'].astype("category")
plyaer_name['team'] = plyaer_name['team'].astype("category")
plyaer_name['match_type_number'] = plyaer_name['match_type_number'].astype("int16")
plyaer_name['match_type'] = plyaer_name['match_type'].astype("category")
plyaer_name['venue'] = plyaer_name['venue'].astype("category")

In [7]:
plyaer_name.to_csv("T20_Players_Name.csv",index=False)

**MATHE INFO CSV CLEANING**

In [8]:
matches_info.head()

,Unnamed: 0,city,event,stage,dates,match_type,match_type_number,player_of_match,winner,winner_by,overs,season,team_type,team1,team2,toss_winner,toss_decision,venue
0,0,NaN,Pakistan v West Indies T20I Series,NaN,2016-09-23,T20,568,['Imad Wasim'],Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium
1,1,NaN,Pakistan v West Indies T20I Series,NaN,2016-09-23,T20,568,['Imad Wasim'],Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium
2,2,NaN,Pakistan v West Indies T20I Series,NaN,2016-09-23,T20,568,['Imad Wasim'],Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium
3,3,NaN,Pakistan v West Indies T20I Series,NaN,2016-09-23,T20,568,['Imad Wasim'],Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium
4,4,NaN,Pakistan v West Indies T20I Series,NaN,2016-09-23,T20,568,['Imad Wasim'],Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium

In [9]:
matches_info = matches_info.drop("Unnamed: 0",axis=1)  #droped the unecessary column

In [10]:
matches_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               200 non-null    object
 1   event              237 non-null    object
 2   stage              19 non-null     object
 3   dates              248 non-null    object
 4   match_type         248 non-null    object
 5   match_type_number  248 non-null    int64
 6   player_of_match    239 non-null    object
 7   winner             248 non-null    object
 8   winner_by          248 non-null    object
 9   overs              248 non-null    int64
 10  season             248 non-null    object
 11  team_type          248 non-null    object
 12  team1              248 non-null    object
 13  team2              248 non-null    object
 14  toss_winner        248 non-null    object
 15  toss_decision      248 non-null    object
 16  venue              248 non-null    object
dtypes: int64(2), object(15)
memory usage: 33.1+ KB

In [11]:
#Converting to suitable types for memory efficiency
matches_info['match_type_number'] = matches_info['match_type_number'].astype('int16')
matches_info['overs'] = matches_info['overs'].astype('int16')
matches_info['city'] = matches_info['city'].astype('category')
matches_info['event'] = matches_info['event'].astype('category')
matches_info['stage'] = matches_info['stage'].astype('category')
matches_info['dates'] = matches_info['dates'].astype('category')
matches_info['match_type'] = matches_info['match_type'].astype('category')
matches_info['winner'] = matches_info['winner'].astype('category')
matches_info['season'] = matches_info['season'].astype('category')
matches_info['team_type'] = matches_info['team_type'].astype('category')
matches_info['team1'] = matches_info['team1'].astype('category')
matches_info['team2'] = matches_info['team2'].astype('category')
matches_info['toss_winner'] = matches_info['toss_winner'].astype('category')
matches_info['toss_decision'] = matches_info['toss_decision'].astype('category')
matches_info['venue'] = matches_info['venue'].astype('category')

# problem resolving in two colums:
**1: player_of_match has list type <br>
  2: winners_by has dict type**

In [12]:
import ast

In [13]:
matches_info['player_of_match'] = matches_info['player_of_match'].fillna("['No Player']")

In [14]:
#In this first we extracted the list from the string and then we removed the list from the data cuz list of one player not 
# make sense
matches_info['player_of_match'] = matches_info['player_of_match'].apply(lambda x : ast.literal_eval(x))
matches_info['player_of_match'] = matches_info['player_of_match'].apply(lambda x : x[0])

In [15]:
matches_info.to_csv("T20_Matches_Info.csv")

In [16]:
Pakistan_T20_Matches_Information.head()

,Team,Over,Batter,Bowler,Non_Striker,Runs_Batter,Runs_Extras,Runs_Total,Wickets,fielder_name,kind,player_out,match_type_number
0,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,0,0,0,0,NaN,NaN,NaN,1002
1,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,1,0,1,0,NaN,NaN,NaN,1002
2,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
3,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
4,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,2,0,2,0,NaN,NaN,NaN,1002

In [17]:
Pakistan_T20_Matches_Information['Over'] = Pakistan_T20_Matches_Information['Over'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Batter'] = Pakistan_T20_Matches_Information['Runs_Batter'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Extras'] = Pakistan_T20_Matches_Information['Runs_Extras'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Total'] = Pakistan_T20_Matches_Information['Runs_Total'].astype('int16')
Pakistan_T20_Matches_Information['Wickets'] = Pakistan_T20_Matches_Information['Wickets'].astype('int16')
Pakistan_T20_Matches_Information['Team'] = Pakistan_T20_Matches_Information['Team'].astype('category')
Pakistan_T20_Matches_Information['Batter'] = Pakistan_T20_Matches_Information['Batter'].astype('category')
Pakistan_T20_Matches_Information['Bowler'] = Pakistan_T20_Matches_Information['Bowler'].astype('category')
Pakistan_T20_Matches_Information['Non_Striker'] = Pakistan_T20_Matches_Information['Non_Striker'].astype('category')
Pakistan_T20_Matches_Information['fielder_name'] = Pakistan_T20_Matches_Information['fielder_name'].fillna('Unknown')
Pakistan_T20_Matches_Information['fielder_name'] = Pakistan_T20_Matches_Information['fielder_name'].astype('category')
Pakistan_T20_Matches_Information['kind'] = Pakistan_T20_Matches_Information['kind'].fillna('Not Out')
Pakistan_T20_Matches_Information['kind'] = Pakistan_T20_Matches_Information['kind'].astype('category')
Pakistan_T20_Matches_Information['player_out'] = Pakistan_T20_Matches_Information['player_out'].fillna('Not Out')
Pakistan_T20_Matches_Information['player_out'] = Pakistan_T20_Matches_Information['player_out'].astype('category')
Pakistan_T20_Matches_Information['match_type_number'] = pd.to_numeric(Pakistan_T20_Matches_Information['match_type_number'], errors='coerce')
Pakistan_T20_Matches_Information['match_type_number'] = Pakistan_T20_Matches_Information['match_type_number'] .fillna(Pakistan_T20_Matches_Information['match_type_number'].mean())

In [24]:
new = pd.read_csv("Pakistan_T20_Players_Innings_Info.csv")

In [20]:
int(Pakistan_T20_Matches_Information['match_type_number'].mean())

950

In [25]:
new

,Unnamed: 0,Team,Over,Batter,Bowler,Non_Striker,Runs_Batter,Runs_Extras,Runs_Total,Wickets,fielder_name,kind,player_out,match_type_number
0,0,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,0,0,0,0,Unknown,Not Out,Not Out,1002.0
1,1,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,1,0,1,0,Unknown,Not Out,Not Out,1002.0
2,2,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,Unknown,Not Out,Not Out,1002.0
3,3,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,Unknown,Not Out,Not Out,1002.0
4,4,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,2,0,2,0,Unknown,Not Out,Not Out,1002.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56229,56229,Pakistan,18,Sarfraz Ahmed,B Muzarabani,Shoaib Malik,2,0,2,0,Unknown,Not Out,Not Out,685.0
56230,56230,Pakistan,18,Sarfraz Ahmed,B Muzarabani,Shoaib Malik,4,0,4,0,Unknown,Not Out,Not Out,685.0
56231,56231,Pakistan,18,Sarfraz Ahmed,B Muzarabani,Shoaib Malik,1,0,1,0,Unknown,Not Out,Not Out,685.0
56232,56232,Pakistan,18,Shoaib Malik,B Muzarabani,Sarfraz Ahmed,0,0,0,0,Unknown,Not Out,Not Out,685.0
56233,56233,Pakistan,19,Sarfraz Ahmed,CB Mpofu,Shoaib Malik,4,0,4,0,Unknown,Not Out,Not Out,685.0