# Determinig Top T20 Team Of Pakistan

In [18]:
import pandas as pd
import json
import os

In [19]:
#Reading the Json file containing Raw Data of Pakistani Players
folder_path = r"C:\Users\4A\Documents\projects\cricket project"

**Extracting the Json file contatinig T20 data Only**

In [20]:
T20_FILES = []
for file_name in os.listdir(folder_path):
    if file_name.endswith('.json'):
        file_path = os.path.join(folder_path, file_name)
        try:
            with open(file_path, 'r') as json_file:
                data = json.load(json_file)
            
            # Check the condition
            if data.get('info', {}).get('match_type') == 'T20':
                T20_FILES.append(file_name)
        except (json.JSONDecodeError, FileNotFoundError, KeyError) as e:
            print(f"Error processing {file_name}: {e}")

# Print the list of T20 files
print("T20_FILES:", len(T20_FILES))

T20_FILES: 243

In [21]:
match_information={ 
'city':[],
'event':[],
'stage':[],
'dates':[],
'match_type':[],
'match_type_number':[],
'winner':[],
'winner_by':[],
'overs':[],
'season':[],
'team_type':[],
'team1':[],
'team2':[],
'toss_winner':[],
'toss_decision':[],
'venue':[]
}

players_infomation={
    'name':[],
    'team':[],
    'match_type_number':[],
    'match_type':[],
    'venue':[]
}

In [22]:
def extract_match_info(rawdata):
    if 'city' in rawdata['info']:
        match_information['city'].append(rawdata['info']['city'])
    else:
        match_information['city'].append(None)
    if 'event' in rawdata['info']:
        match_information['event'].append(rawdata['info']['event']['name'])
        if 'stage' in rawdata['info']['event']:
            match_information['stage'].append(rawdata['info']['event']['stage'])
        else:
            match_information['stage'].append(None)
    else:
        match_information['event'].append(None)
        match_information['stage'].append(None)
        
    match_information['dates'].append(''.join(rawdata['info']['dates']))
    match_information['match_type'].append(rawdata['info']['match_type'])
    match_information['match_type_number'].append(rawdata['info']['match_type_number'])
    if 'winner' in rawdata['info']['outcome']:
        match_information['winner'].append(rawdata['info']['outcome']['winner'])
        match_information['winner_by'].append(rawdata['info']['outcome']['by'])
    else:
        match_information['winner'].append('no result')
        match_information['winner_by'].append('no result')
    match_information['overs'].append(rawdata['info']['overs'])
    match_information['season'].append(rawdata['info']['season'])
    match_information['team_type'].append(rawdata['info']['team_type'])
    match_information['team1'].append(rawdata['info']['teams'][0])
    match_information['team2'].append(rawdata['info']['teams'][1])
    match_information['toss_winner'].append(rawdata['info']['toss']['winner'])
    match_information['toss_decision'].append(rawdata['info']['toss']['decision'])
    match_information['venue'].append(rawdata['info']['venue'])
    
def players_info(rawdata):
    for x in rawdata['info']['players']:
        for y in rawdata['info']['players'][x]:
            players_infomation['name'].append(y)
            players_infomation['match_type_number'].append(rawdata['info']['match_type_number'])
            players_infomation['match_type'].append(rawdata['info']['match_type'])
            players_infomation['team'].append(x)
            players_infomation['venue'].append(rawdata['info']['venue'])

In [6]:
def innings_data(raw_data):
    innings_data = raw_data['innings']
    rows = []
    for inning in innings_data:
        team = inning['team']
        for over in inning['overs']:
            over_number = over['over']
            for delivery in over['deliveries']:
                row = {
                    'Team': team,
                    'Over': over_number,
                    'Batter': delivery['batter'],
                    'Bowler': delivery['bowler'],
                    'Non_Striker': delivery.get('non_striker', None),
                    'Runs_Batter': delivery['runs']['batter'],
                    'Runs_Extras': delivery['runs'].get('extras', 0),
                    'Runs_Total': delivery['runs']['total']
                }
                if 'wickets' in delivery:
                    row['Wickets']  = 1
                    row['player_out'] = delivery['wickets'][0]['player_out']
                    if 'fielders' in delivery['wickets'][0]:
                        row['fielder_name'] = delivery['wickets'][0]['fielders'][0]['name']
                    else:
                         row['fielder_name'] = None
                    row['kind']= delivery['wickets'][0]['kind']
                else:
                    row['Wickets'] = 0
                    row['fielder_name'] = None
                    row['kind'] = None
                
                rows.append(row)
    return pd.DataFrame(rows)

**Extracting Mathces Information From Json File**

In [23]:
for name in T20_FILES:
    print(name) 
    with open(r'C:\Users\4A\Documents\projects\cricket project'+"\\"+ name) as file:
        rawdata = json.load(file)
        extract_match_info(rawdata)

1050217.json
1050219.json
1050221.json
1077947.json
1077948.json
1085495.json
1085496.json
1115807.json
1115808.json
1115809.json
1117821.json
1117822.json
1117824.json
1120291.json
1120292.json
1120293.json
1127300.json
1127301.json
1140069.json
1140070.json
1140071.json
1142913.json
1142914.json
1142916.json
1142917.json
1142919.json
1144161.json
1144162.json
1144163.json
1152840.json
1157372.json
1157373.json
1157374.json
1157375.json
1157376.json
1157377.json
1183527.json
1183528.json
1183529.json
1198244.json
1198245.json
1198246.json
1198489.json
1198490.json
1198491.json
1213058.json
1213059.json
1233464.json
1233465.json
1233466.json
1233959.json
1233960.json
1233961.json
1239540.json
1239541.json
1239542.json
1243019.json
1243020.json
1243021.json
1251575.json
1251576.json
1251577.json
1251578.json
1257183.json
1257184.json
1257185.json
1263164.json
1263165.json
1263166.json
1263167.json
1273727.json
1273730.json
1273742.json
1273752.json
1273755.json
1277974.json
1277975.json
1277976.json
1287773.json
1287774.json
1287775.json
1288316.json
1298150.json
1298158.json
1298163.json
1298170.json
1298175.json
1298177.json
1298179.json
1322334.json
1322335.json
1322337.json
1322339.json
1322340.json
1327228.json
1327229.json
1327230.json
1327231.json
1327232.json
1327233.json
1327234.json
1327270.json
1327274.json
1327276.json
1327280.json
1327281.json
1339614.json
1339615.json
1339616.json
1339617.json
1339618.json
1385688.json
1385690.json
1388216.json
1388217.json
1388218.json
1388219.json
1388220.json
1399114.json
1399119.json
1415711.json
1415719.json
1415722.json
1415736.json
1424829.json
1424830.json
1424831.json
1424832.json
1424833.json
1426552.json
1426553.json
1426554.json
1426830.json
1426831.json
1426832.json
1432211.json
1432212.json
1444652.json
1444653.json
1444654.json
225263.json
287855.json
287862.json
287868.json
287870.json
287875.json
287877.json
287879.json
306989.json
306991.json
343764.json
355996.json
355999.json
356005.json
356008.json
356012.json
356015.json
356017.json
361656.json
361660.json
392615.json
403375.json
406207.json
412680.json
412683.json
412689.json
412693.json
412697.json
412702.json
426392.json
426393.json
426417.json
426418.json
426723.json
426724.json
440945.json
440946.json
461565.json
473918.json
473919.json
473920.json
478279.json
489212.json
523735.json
523736.json
530432.json
531635.json
531636.json
531637.json
533280.json
533283.json
533286.json
533291.json
533294.json
533296.json
538068.json
562437.json
562438.json
567367.json
571148.json
571149.json
571150.json
589306.json
589307.json
645645.json
645647.json
649101.json
649103.json
657633.json
657635.json
659545.json
659547.json
682921.json
682927.json
682949.json
682959.json
685727.json
685729.json
727917.json
742617.json
754039.json
858491.json
860279.json
860281.json
868723.json
868725.json
902649.json
902651.json
902653.json
913663.json
914221.json
914223.json
914225.json
919603.json
919605.json
951333.json
951341.json
951349.json
951355.json
966751.json
966755.json
966759.json
966763.json

**Extracting Players Information From Json File**

In [24]:
for name in T20_FILES:
    print(name) 
    with open(r'C:\Users\4A\Documents\projects\cricket project'+"\\"+ name) as file:
        rawdata = json.load(file)
        players_info(rawdata)

1050217.json
1050219.json
1050221.json
1077947.json
1077948.json
1085495.json
1085496.json
1115807.json
1115808.json
1115809.json
1117821.json
1117822.json
1117824.json
1120291.json
1120292.json
1120293.json
1127300.json
1127301.json
1140069.json
1140070.json
1140071.json
1142913.json
1142914.json
1142916.json
1142917.json
1142919.json
1144161.json
1144162.json
1144163.json
1152840.json
1157372.json
1157373.json
1157374.json
1157375.json
1157376.json
1157377.json
1183527.json
1183528.json
1183529.json
1198244.json
1198245.json
1198246.json
1198489.json
1198490.json
1198491.json
1213058.json
1213059.json
1233464.json
1233465.json
1233466.json
1233959.json
1233960.json
1233961.json
1239540.json
1239541.json
1239542.json
1243019.json
1243020.json
1243021.json
1251575.json
1251576.json
1251577.json
1251578.json
1257183.json
1257184.json
1257185.json
1263164.json
1263165.json
1263166.json
1263167.json
1273727.json
1273730.json
1273742.json
1273752.json
1273755.json
1277974.json
1277975.json
1277976.json
1287773.json
1287774.json
1287775.json
1288316.json
1298150.json
1298158.json
1298163.json
1298170.json
1298175.json
1298177.json
1298179.json
1322334.json
1322335.json
1322337.json
1322339.json
1322340.json
1327228.json
1327229.json
1327230.json
1327231.json
1327232.json
1327233.json
1327234.json
1327270.json
1327274.json
1327276.json
1327280.json
1327281.json
1339614.json
1339615.json
1339616.json
1339617.json
1339618.json
1385688.json
1385690.json
1388216.json
1388217.json
1388218.json
1388219.json
1388220.json
1399114.json
1399119.json
1415711.json
1415719.json
1415722.json
1415736.json
1424829.json
1424830.json
1424831.json
1424832.json
1424833.json
1426552.json
1426553.json
1426554.json
1426830.json
1426831.json
1426832.json
1432211.json
1432212.json
1444652.json
1444653.json
1444654.json
225263.json
287855.json
287862.json
287868.json
287870.json
287875.json
287877.json
287879.json
306989.json
306991.json
343764.json
355996.json
355999.json
356005.json
356008.json
356012.json
356015.json
356017.json
361656.json
361660.json
392615.json
403375.json
406207.json
412680.json
412683.json
412689.json
412693.json
412697.json
412702.json
426392.json
426393.json
426417.json
426418.json
426723.json
426724.json
440945.json
440946.json
461565.json
473918.json
473919.json
473920.json
478279.json
489212.json
523735.json
523736.json
530432.json
531635.json
531636.json
531637.json
533280.json
533283.json
533286.json
533291.json
533294.json
533296.json
538068.json
562437.json
562438.json
567367.json
571148.json
571149.json
571150.json
589306.json
589307.json
645645.json
645647.json
649101.json
649103.json
657633.json
657635.json
659545.json
659547.json
682921.json
682927.json
682949.json
682959.json
685727.json
685729.json
727917.json
742617.json
754039.json
858491.json
860279.json
860281.json
868723.json
868725.json
902649.json
902651.json
902653.json
913663.json
914221.json
914223.json
914225.json
919603.json
919605.json
951333.json
951341.json
951349.json
951355.json
966751.json
966755.json
966759.json
966763.json

**Extracing Inning Information From Json File**

In [34]:
for name in T20_FILES:
    print(name) 
    with open(r'C:\Users\4A\Documents\projects\cricket project'+"\\"+ name) as file:
        rawdata = json.load(file)
        innings_dataFrame = innings_data(rawdata)

1050217.json
1050219.json
1050221.json
1077947.json
1077948.json
1085495.json
1085496.json
1115807.json
1115808.json
1115809.json
1117821.json
1117822.json
1117824.json
1120291.json
1120292.json
1120293.json
1127300.json
1127301.json
1140069.json
1140070.json
1140071.json
1142913.json
1142914.json
1142916.json
1142917.json
1142919.json
1144161.json
1144162.json
1144163.json
1152840.json
1157372.json
1157373.json
1157374.json
1157375.json
1157376.json
1157377.json
1183527.json
1183528.json
1183529.json
1198244.json
1198245.json
1198246.json
1198489.json
1198490.json
1198491.json
1213058.json
1213059.json
1233464.json
1233465.json
1233466.json
1233959.json
1233960.json
1233961.json
1239540.json
1239541.json
1239542.json
1243019.json
1243020.json
1243021.json
1251575.json
1251576.json
1251577.json
1251578.json
1257183.json
1257184.json
1257185.json
1263164.json
1263165.json
1263166.json
1263167.json
1273727.json
1273730.json
1273742.json
1273752.json
1273755.json
1277974.json
1277975.json
1277976.json
1287773.json
1287774.json
1287775.json
1288316.json
1298150.json
1298158.json
1298163.json
1298170.json
1298175.json
1298177.json
1298179.json
1322334.json
1322335.json
1322337.json
1322339.json
1322340.json
1327228.json
1327229.json
1327230.json
1327231.json
1327232.json
1327233.json
1327234.json
1327270.json
1327274.json
1327276.json
1327280.json
1327281.json
1339614.json
1339615.json
1339616.json
1339617.json
1339618.json
1385688.json
1385690.json
1388216.json
1388217.json
1388218.json
1388219.json
1388220.json
1399114.json
1399119.json
1415711.json
1415719.json
1415722.json
1415736.json
1424829.json
1424830.json
1424831.json
1424832.json
1424833.json
1426552.json
1426553.json
1426554.json
1426830.json
1426831.json
1426832.json
1432211.json
1432212.json
1444652.json
1444653.json
1444654.json
225263.json
287855.json
287862.json
287868.json
287870.json
287875.json
287877.json
287879.json
306989.json
306991.json
343764.json
355996.json
355999.json
356005.json
356008.json
356012.json
356015.json
356017.json
361656.json
361660.json
392615.json
403375.json
406207.json
412680.json
412683.json
412689.json
412693.json
412697.json
412702.json
426392.json
426393.json
426417.json
426418.json
426723.json
426724.json
440945.json
440946.json
461565.json
473918.json
473919.json
473920.json
478279.json
489212.json
523735.json
523736.json
530432.json
531635.json
531636.json
531637.json
533280.json
533283.json
533286.json
533291.json
533294.json
533296.json
538068.json
562437.json
562438.json
567367.json
571148.json
571149.json
571150.json
589306.json
589307.json
645645.json
645647.json
649101.json
649103.json
657633.json
657635.json
659545.json
659547.json
682921.json
682927.json
682949.json
682959.json
685727.json
685729.json
727917.json
742617.json
754039.json
858491.json
860279.json
860281.json
868723.json
868725.json
902649.json
902651.json
902653.json
913663.json
914221.json
914223.json
914225.json
919603.json
919605.json
951333.json
951341.json
951349.json
951355.json
966751.json
966755.json
966759.json
966763.json

In [26]:
for x,y in match_information.items():
    print(f'{x}: length {len(y)}')

city: length 243
event: length 243
stage: length 243
dates: length 243
match_type: length 243
match_type_number: length 243
winner: length 243
winner_by: length 243
overs: length 243
season: length 243
team_type: length 243
team1: length 243
team2: length 243
toss_winner: length 243
toss_decision: length 243
venue: length 243

# **Take a Look at Extracted Information**

In [27]:
pd.DataFrame(match_information)

,city,event,stage,dates,match_type,match_type_number,winner,winner_by,overs,season,team_type,team1,team2,toss_winner,toss_decision,venue
0,None,Pakistan v West Indies T20I Series,None,2016-09-23,T20,568,Pakistan,{'wickets': 9},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Dubai International Cricket Stadium
1,None,Pakistan v West Indies T20I Series,None,2016-09-24,T20,569,Pakistan,{'runs': 16},20,2016/17,international,Pakistan,West Indies,West Indies,field,Dubai International Cricket Stadium
2,Abu Dhabi,Pakistan v West Indies T20I Series,None,2016-09-27,T20,570,Pakistan,{'wickets': 8},20,2016/17,international,Pakistan,West Indies,Pakistan,field,Sheikh Zayed Stadium
3,Barbados,Pakistan in West Indies T20I Series,None,2017-03-26,T20,602,Pakistan,{'wickets': 6},20,2017,international,West Indies,Pakistan,Pakistan,field,"Kensington Oval, Bridgetown"
4,Trinidad,Pakistan in West Indies T20I Series,None,2017-03-30,T20,603,Pakistan,{'runs': 3},20,2017,international,West Indies,Pakistan,West Indies,field,"Queen's Park Oval, Port of Spain"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,Chandigarh,World T20,Super 10,2016-03-25,T20,548,Australia,{'runs': 21},20,2015/16,international,Australia,Pakistan,Australia,bat,"Punjab Cricket Association IS Bindra Stadium, ..."
239,Mirpur,Asia Cup,None,2016-02-27,T20,512,India,{'wickets': 5},20,2015/16,international,India,Pakistan,India,field,Shere Bangla National Stadium
240,Mirpur,Asia Cup,None,2016-02-29,T20,514,Pakistan,{'wickets': 7},20,2015/16,international,Pakistan,United Arab Emirates,United Arab Emirates,bat,Shere Bangla National Stadium
241,Mirpur,Asia Cup,None,2016-03-02,T20,516,Bangladesh,{'wickets': 5},20,2015/16,international,Bangladesh,Pakistan,Pakistan,bat,Shere Bangla National Stadium
242,Mirpur,Asia Cup,None,2016-03-04,T20,518,Pakistan,{'wickets': 6},20,2015/16,international,Pakistan,Sri Lanka,Pakistan,field,Shere Bangla National Stadium

In [32]:
pd.DataFrame(players_infomation)

,name,team,match_type_number,match_type,venue
0,Sharjeel Khan,Pakistan,568,T20,Dubai International Cricket Stadium
1,Khalid Latif,Pakistan,568,T20,Dubai International Cricket Stadium
2,Babar Azam,Pakistan,568,T20,Dubai International Cricket Stadium
3,Shoaib Malik,Pakistan,568,T20,Dubai International Cricket Stadium
4,Umar Akmal,Pakistan,568,T20,Dubai International Cricket Stadium
...,...,...,...,...,...
5342,N Dickwella,Sri Lanka,518,T20,Shere Bangla National Stadium
5343,NLTC Perera,Sri Lanka,518,T20,Shere Bangla National Stadium
5344,KMDN Kulasekara,Sri Lanka,518,T20,Shere Bangla National Stadium
5345,HMRKB Herath,Sri Lanka,518,T20,Shere Bangla National Stadium
5346,PVD Chameera,Sri Lanka,518,T20,Shere Bangla National Stadium

In [35]:
innings_dataFrame

,Team,Over,Batter,Bowler,Non_Striker,Runs_Batter,Runs_Extras,Runs_Total,Wickets,fielder_name,kind,player_out
0,Sri Lanka,0,LD Chandimal,Mohammad Amir,TM Dilshan,0,0,0,0,None,None,NaN
1,Sri Lanka,0,LD Chandimal,Mohammad Amir,TM Dilshan,0,0,0,0,None,None,NaN
2,Sri Lanka,0,LD Chandimal,Mohammad Amir,TM Dilshan,0,0,0,0,None,None,NaN
3,Sri Lanka,0,LD Chandimal,Mohammad Amir,TM Dilshan,1,0,1,0,None,None,NaN
4,Sri Lanka,0,TM Dilshan,Mohammad Amir,LD Chandimal,0,1,1,0,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
234,Pakistan,18,Shoaib Malik,KMDN Kulasekara,Umar Akmal,1,0,1,0,None,None,NaN
235,Pakistan,18,Umar Akmal,KMDN Kulasekara,Shoaib Malik,6,0,6,0,None,None,NaN
236,Pakistan,18,Umar Akmal,KMDN Kulasekara,Shoaib Malik,0,0,0,1,NLTC Perera,caught,Umar Akmal
237,Pakistan,19,Shoaib Malik,NLTC Perera,Iftikhar Ahmed,0,0,0,0,None,None,NaN
238,Pakistan,19,Shoaib Malik,NLTC Perera,Iftikhar Ahmed,1,0,1,0,None,None,NaN

In [61]:
import os
import pandas as pd

def contact_match_FILES(csvs_list):
    # Define the root directory path
    directory = r"C:\Users\4A\Documents\projects"
    
    # Ensure the directory exists
    if not os.path.exists(directory):
        print("The specified directory does not exist.")
        return
    
    # Walk through the directory and its subdirectories
    for root, dirs, files in os.walk(directory):
        # Filter out only CSV files and append their names to the list
        for file in files:
            if file.endswith('.csv'):
                # Append only the file name, not the full path
                csvs_list.append(file)
    
    # Output the final list of CSV files found
    print(f"Found {len(csvs_list)} CSV files:")

In [62]:
csvs_list = []
contact_match_FILES(csvs_list)
csvs_list.remove("match_info.csv")
csvs_list.remove("Player_name.csv")

Found 246 CSV files:

In [63]:
def contact_match_files(csvs_list):
    firstFile = pd.read_csv(csvs_list[0])
    firstFile['match_type_number'] = csvs_list[0].split('_')[1]
    for i in range(1,len(csvs_list)):
        df = pd.read_csv(csvs_list[i])
        df['match_type_number'] = csvs_list[i].split('_')[1]
        firstFile = pd.concat([firstFile, df])
    
    return firstFile

In [64]:
concat_File = contact_match_files(csvs_list)

In [65]:
concat_File['match_type_number']=concat_File['match_type_number'].str.replace('.csv','')

In [50]:
concat_File.to_csv('Pakistan_T20_Matches_Information.csv', index=False)

In [66]:
concat_File.head()

,Team,Over,Batter,Bowler,Non_Striker,Runs_Batter,Runs_Extras,Runs_Total,Wickets,fielder_name,kind,player_out,match_type_number
0,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,0,0,0,0,NaN,NaN,NaN,1002
1,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,1,0,1,0,NaN,NaN,NaN,1002
2,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
3,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
4,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,2,0,2,0,NaN,NaN,NaN,1002

In [103]:
concat_File = pd.read_csv('Pakistan_T20_Matches_Information.csv')
Pakistan_T20_Matches_Information = pd.read_csv('Pakistan_T20_Matches_Information.csv')

In [104]:
Pakistan_T20_Matches_Information.head()

,Team,Over,Batter,Bowler,Non_Striker,Runs_Batter,Runs_Extras,Runs_Total,Wickets,fielder_name,kind,player_out,match_type_number
0,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,0,0,0,0,NaN,NaN,NaN,1002
1,Pakistan,0,Babar Azam,MA Starc,Fakhar Zaman,1,0,1,0,NaN,NaN,NaN,1002
2,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
3,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,0,0,0,0,NaN,NaN,NaN,1002
4,Pakistan,0,Fakhar Zaman,MA Starc,Babar Azam,2,0,2,0,NaN,NaN,NaN,1002

In [105]:
Pakistan_T20_Matches_Information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56234 entries, 0 to 56233
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Team               56234 non-null  object
 1   Over               56234 non-null  int64
 2   Batter             56234 non-null  object
 3   Bowler             56234 non-null  object
 4   Non_Striker        56234 non-null  object
 5   Runs_Batter        56234 non-null  int64
 6   Runs_Extras        56234 non-null  int64
 7   Runs_Total         56234 non-null  int64
 8   Wickets            56234 non-null  int64
 9   fielder_name       2114 non-null   object
 10  kind               3063 non-null   object
 11  player_out         3063 non-null   object
 12  match_type_number  56234 non-null  object
dtypes: int64(5), object(8)
memory usage: 5.6+ MB

In [106]:
Pakistan_T20_Matches_Information['Over'] = Pakistan_T20_Matches_Information['Over'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Batter'] = Pakistan_T20_Matches_Information['Runs_Batter'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Extras'] = Pakistan_T20_Matches_Information['Runs_Extras'].astype('int16')
Pakistan_T20_Matches_Information['Runs_Total'] = Pakistan_T20_Matches_Information['Runs_Total'].astype('int16')
Pakistan_T20_Matches_Information['Wickets'] = Pakistan_T20_Matches_Information['Wickets'].astype('int16')
Pakistan_T20_Matches_Information['Team'] = Pakistan_T20_Matches_Information['Team'].astype('category')
Pakistan_T20_Matches_Information['Batter'] = Pakistan_T20_Matches_Information['Batter'].astype('category')
Pakistan_T20_Matches_Information['Bowler'] = Pakistan_T20_Matches_Information['Bowler'].astype('category')
Pakistan_T20_Matches_Information['Non_Striker'] = Pakistan_T20_Matches_Information['Non_Striker'].astype('category')
Pakistan_T20_Matches_Information['fielder_name'] = Pakistan_T20_Matches_Information['fielder_name'].fillna('Unknown')
Pakistan_T20_Matches_Information['fielder_name'] = Pakistan_T20_Matches_Information['fielder_name'].astype('category')
Pakistan_T20_Matches_Information['kind'] = Pakistan_T20_Matches_Information['kind'].fillna('Not Out')
Pakistan_T20_Matches_Information['kind'] = Pakistan_T20_Matches_Information['kind'].astype('category')
Pakistan_T20_Matches_Information['player_out'] = Pakistan_T20_Matches_Information['player_out'].fillna('Not Out')
Pakistan_T20_Matches_Information['player_out'] = Pakistan_T20_Matches_Information['player_out'].astype('category')
Pakistan_T20_Matches_Information['match_type_number'] = pd.to_numeric(Pakistan_T20_Matches_Information['match_type_number'], errors='coerce')

In [107]:
Pakistan_T20_Matches_Information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56234 entries, 0 to 56233
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Team               56234 non-null  category
 1   Over               56234 non-null  int16
 2   Batter             56234 non-null  category
 3   Bowler             56234 non-null  category
 4   Non_Striker        56234 non-null  category
 5   Runs_Batter        56234 non-null  int16
 6   Runs_Extras        56234 non-null  int16
 7   Runs_Total         56234 non-null  int16
 8   Wickets            56234 non-null  int16
 9   fielder_name       56234 non-null  category
 10  kind               56234 non-null  category
 11  player_out         56234 non-null  category
 12  match_type_number  55990 non-null  float64
dtypes: category(7), float64(1), int16(5)
memory usage: 1.7 MB